export { default as CInput } from "./Input";
export { default as CSelect } from "./Select";
export { default as CRangePicker } from "./RangePicker";
export { default as CDatePicker } from "./DatePicker";
export { default as CButton } from "./Button";
export { default as CTable } from "./Table";
export { default as CPagination } from "./Pagination";
export { default as CTabs } from "./Tabs";
export { default as CTag } from "./Tag";
